--- 
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0d7a109bf30624c99
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHsecurityGroup


  SSHsecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: simple sg
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22


